### PR TITLE
fix typo in cursor selection

### PR DESCRIPTION
**Pull request by fiendish**

### CODE REVIEW

**Comment by fiendish** [comment]
Though, honestly, I think you probably want to move the cursor selection up to the 'default' style instead of having a separate 'select' style, so that it changes on mouseover.

**Comment by ehrenfeu** [comment]
Thanks a lot, @fiendish !
Would you be willing to implement the changes you suggested in your additional comment?

**Comment by fiendish** [comment]
Done.
https://github.com/OpenSeaMap/online_chart/pull/65

**Comment by fiendish** [comment]
I also have a working openlayers 3 class for displaying ais data. Is there any current interest in migrating to ol3?

**Comment by Dirk--** [comment]
Gabi (@roeger) is working on new ol3 map.

**Comment by roeger** [comment]
@fiendish I am highly interested in your AIS data class. Do you want to integrate it yourself or should I do it? I am working in https://github.com/ehrenfeu/oseam_online_chart (ol3 branch, currently everything in subdirectory openlayers3). The code is still very alpha, so if you only want to contribute the class, you could for example put it into the ol3 folder there.

**Comment by ehrenfeu** [comment]
@fiendish a preview of the OL3 repository mentioned above is available here:
http://openseamap.he1ix.org/openlayers3/map.html

**Pull request merged**
