### PR TITLE
Switch base tiles back to OpenStreetMap (reverted)

### PR DESCRIPTION
**Pull request by aAXEe**
revert from d555a3af73bbbc5367ac8c3998930f2c4eb77e68

### CODE REVIEW

**Comment by mojoaxel** [comment]
`http://osm1.wtnet.de/tiles/base/` seams not to be online!?

**Comment by Nautic** [comment]
Am 21.02.2016 um 23:43 schrieb Alexander Wunschik:
> |http://osm1.wtnet.de/tiles/base/| seams not to be online!?

Im Monitoring sehe ich keine Auffälligkeiten...

**Comment by aAXEe** [comment]
The dns record seems to be outdated. 
From the monitoring: the IP seems to be 213.209.102.17 (the whois reports: d1-port-17.dialin.wtnet.de). The following url works for getting tiles: http://213.209.102.17/tiles/base/0/0/0.png or http://d1-port-17.dialin.wtnet.de/tiles/base/0/0/0.png

The monitoring only checks the ping for this IP. No checks for HTTP serving or DNS lookup are performed.
As far as i know the goal is to reach this service at bravo.openseamap.org and the tiles at t2.openseamap.org. I guess that the DNS is not configured for that.

**Comment by wschildbach** [comment]
I am confused by the PR. Is this trying to point to OSM or to our own servers? The former is currently, and the latter is not working (and will not until our tile server is up, which takes longer apparently).

So, can we close this one? 

Wolfgang

**Pull request closed without merging**
