### PR TITLE
fix wikipedia layer by using a newer proxy 

### PR DESCRIPTION
**Pull request by aAXEe**

### CODE REVIEW

**Comment by ehrenfeu** [comment]
Hi @aAXEe,

unfortunately your changes don't work for me. I've tried them on my testing server, which is installed from the same scripts as map.openseamap.org, and it is producing PHP errors:

    PHP Fatal error:  Call to undefined function curl_init() in /srv/osm/map/api/proxy-wikipedia.php on line 16

I *guess* this could be solved by installing the `php5-curl` package. Will try...

**Comment by ehrenfeu** [comment]
Alright, installing the above mentioned package solves the errors and makes the wikipedia layers work again. I will have to check if I do have enough permissions to do this on the production machine.

Otherwise the patch seems to be fine, so I'm merging it!

One more remark @aAXEe: please put stuff like the docker scripts into a separate PR next time.

**Comment by aAXEe** [comment]
Thanks for merging!

Yes closing this one after seeing my error with git would have been better. Sorry!

**Comment by ehrenfeu** [comment]
No problem! Thanks for the fix!

**Pull request merged**
