### PR TITLE
bugfix: AIS layer visibility did not honor cookie setting

### PR DESCRIPTION
**Pull request by wschildbach**

### CODE REVIEW

**Comment by wschildbach** [comment]
This fixes #120.

**Comment by wschildbach** [comment]
@aAXEe, something funky happened here. My original bugfix was 655d128, and contained some changes. The actual commit 35507a9 does not seem to contain any changes, and indeed the master branch seems to not be fixed. Can you double-check what happened? I am fairly new to this git & github business so have no idea what could have gone wrong.

**Comment by aAXEe** [comment]
That looks pretty strange.

If tested it some more times #128 #129 ... all with the same effect.

Afterwards I analyzed the commit history and found the reason:

The changes from https://github.com/OpenSeaMap/online_chart/commit/655d12800ee2daeafd68152aa57c98d88869eb42 were already included in #114 with commit 17c79c885d175697393ffdb26d6ecac55b9bc90c.
However the branch on your merge request was created earlier so the changes were not included where.

> I am fairly new to this git & github business so have no idea what could have gone wrong.

No worries, I work every day with git and even for me it took some tries and investigation to recognise this.

**Comment by wschildbach** [comment]
Thanks 👍 Let me know when you have deployed these changes so that we can close a few more issues.

**Comment by aAXEe** [comment]
The current master is deployed on alpha

https://map.openseamap.org

**Pull request merged**
